### ISSUE TITLE
IndexError: index 6 is out of bounds for dimension 1 with size 6I

### ISSUE THREAD

**Issue by StarBlue98** [XinzeLee/RotateObjectDetection#14]
I have modified my label into the format (class, cx, cy, w, h, cos, sin)，and I sucessfully train UCAS-AOD you provided, but I meet this problem when I train my own dataset.
my label is as  follows:     0 1244.5523 399.0501 86.4318 225.7462 0.3616157183568731 0.9323272345251117 
![image](https://user-images.githubusercontent.com/94182491/141890189-28b45087-2233-4e0c-af9b-633c88a71599.png)

Traceback (most recent call last):
  File "rotate_train.py", line 553, in <module>
    train(hyp, opt, device, tb_writer, rotate=opt.rotate)
  File "rotate_train.py", line 103, in train
    model = Model(opt.cfg, ch=3, nc=nc, anchors=hyp.get('anchors')).to(device)  # create
  File "/home/cdzk/LanXin/R-yolov5/rotate-yolov5/models/yolo.py", line 341, in __init__
    super(Rotate_Model, self).__init__(cfg, ch, nc, anchors)
  File "/home/cdzk/LanXin/R-yolov5/rotate-yolov5/models/yolo.py", line 110, in __init__
    self._initialize_biases()  # only run once
  File "/home/cdzk/LanXin/R-yolov5/rotate-yolov5/models/yolo.py", line 366, in _initialize_biases
    b.data[:, 6] += math.log(8 / (640 / s) ** 2)  # obj (8 objects per 640 image)
IndexError: index 6 is out of bounds for dimension 1 with size 6

![image](https://user-images.githubusercontent.com/94182491/141890153-f020cd8f-a4c4-41a8-8ae7-dc44f1c725c5.png)

could you know what can I do to revise this ?
Thank you for your help!

**Comment by StarBlue98** [comment]
By the way , my own data has only one class, so when I train this model, what else should I pay attention to ?

**Comment by Camilochiang** [comment]
@AllieLan How did you solve ur problem? Just curious

**Comment by StarBlue98** [comment]
Oh, I found that the problem is caused by using original yolov5s.yaml which only includes 3 pairs of anchor ratios, not 5 pairs that you revised in models/rotate_yolov5s_ucas.yaml.
