### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by nhathoang0110** [XinzeLee/RotateObjectDetection#2]
what is your format annotation for trainning ? I see 6 values.

**Comment by XinzeLee** [comment]
Thanks for your interests!
Not exactly 6. There are 7 entities in the label files: class_id, cx, cy, width, height, real, imaginary.

**Comment by muhammedakyuzlu** [comment]
Hello, Isn't it class_id, cx, cy, width, height, cos theta , sin theta ?
What is real, imaginary stand for?

**Comment by XinzeLee** [comment]
real and imaginary are the same as cos theta and sin theta
